# config.yaml
name: "Homepage"
description: "The highly customizable dashboard for your homelab."
version: "1.10.1"
slug: "homepage"
startup: "application"
boot: "auto"
ingress: true
ingress_port: 3000 # Homepage internal default is 3000
panel_icon: "mdi:home-screen"
panel_title: "Homepage"
map:
  - addon_config:rw
docker_api: true